version: "3"

# To test prod
services:
  watcharr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      - ./container_data:/data
